"""initial schema: gas stations and reviews

Revision ID: 64bca0855c2f
Revises:
Create Date: 2026-10-05 14:26:46.347502

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "64bca0855c2f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gasstation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("chain", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "review",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column(
            "bathroom_type",
            sa.Enum("women", "men", "unisex_or_family", "accessible", "other", name="bathroomtype"),
            nullable=False,
        ),
        sa.Column("cleanliness", sa.Integer(), nullable=False),
        sa.Column("has_soap", sa.Boolean(), nullable=False),
        sa.Column("has_toilet_paper", sa.Boolean(), nullable=False),
        sa.Column("is_wheelchair_accessible", sa.Boolean(), nullable=False),
        sa.Column("has_baby_changing_table", sa.Boolean(), nullable=False),
        sa.Column("feels_safe", sa.Boolean(), nullable=False),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["gasstation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("review")
    op.drop_table("gasstation")
    # ### end Alembic commands ###
